stages:
  preprocess:
    foreach:
    - train
    - validation
    - test
    do:
      cmd: pipenv run python sherlock/scripts/preprocess.py ${item}
      deps:
      - Pipfile.lock
      - data/data/raw/${item}_values.parquet
      - data/data/raw/${item}_values.parquet
      - data/data/raw/${item}_values.parquet
      - features/par_vec_trained_400.pkl
      - features/par_vec_trained_400.pkl.docvecs.vectors_docs.npy
      - features/par_vec_trained_400.pkl.trainables.syn1neg.npy
      - features/par_vec_trained_400.pkl.wv.vectors.npy
      - sherlock/__init__.py
      - sherlock/features/__init__.py
      - sherlock/features/bag_of_characters.py
      - sherlock/features/bag_of_words.py
      - sherlock/features/helpers.py
      - sherlock/features/paragraph_vectors.py
      - sherlock/features/preprocessing.py
      - sherlock/features/regexes.py
      - sherlock/features/stats_helper.py
      - sherlock/features/word_embeddings.py
      - sherlock/functional.py
      - sherlock/global_state.py
      - sherlock/helpers.py
      - sherlock/scripts/preprocess.py
      outs:
      - data/data/processed/${item}.csv
  convert:
    cmd: pipenv run python sherlock/scripts/convert.py
    deps:
    - Pipfile.lock
    - data/data/processed/test.csv
    - data/data/processed/train.csv
    - data/data/processed/validation.csv
    - sherlock/scripts/convert.py
    outs:
    - data/data/processed/test.parquet
    - data/data/processed/train.parquet
    - data/data/processed/validation.parquet
  regex_feature_selection:
    cmd: pipenv run python sherlock/scripts/regex_feature_selection.py
    deps:
    - Pipfile.lock
    - data/data/processed/train.parquet
    - data/data/raw/train_labels.parquet
    - sherlock/scripts/regex_feature_selection.py
    outs:
    - features/feature_column_identifiers/regex_col.tsv
  train:
    cmd: pipenv run python sherlock/scripts/train.py
    params:
    - params.yaml:
    deps:
    - Pipfile.lock
    - data/data/processed/test.parquet
    - data/data/processed/train.parquet
    - data/data/processed/validation.parquet
    - data/data/raw/test_labels.parquet
    - data/data/raw/train_labels.parquet
    - data/data/raw/validation_labels.parquet
    - features/feature_column_identifiers
    - sherlock/__init__.py
    - sherlock/deploy/__init__.py
    - sherlock/deploy/helpers.py
    - sherlock/deploy/model.py
    - sherlock/scripts/train.py
    outs:
    - model_files/classes_retrained_sherlock.npy
    - model_files/retrained_sherlock_model.json
    - model_files/retrained_sherlock_weights.h5
    metrics:
    - dvclive/metrics.json:
        cache: false
    plots:
    - dvclive/plots:
        cache: false
  generate_confusion_matrix:
    cmd: pipenv run python sherlock/scripts/generate_confusion_matrix.py
    deps:
    - model_files/classes_retrained_sherlock.npy
    - model_files/retrained_sherlock_model.json
    - model_files/retrained_sherlock_weights.h5
    - sherlock/__init__.py
    - sherlock/deploy/__init__.py
    - sherlock/deploy/helpers.py
    - sherlock/deploy/model.py
    - sherlock/scripts/generate_confusion_matrix.py
    outs:
    - model_files/retrained_sherlock_confusion.txt
  update deps:
    cmd: pipenv run python update_deps.py
    deps:
    - sherlock
    - update_deps.py
