epochs: 100
dropout_rate: 0.35
learning_rate: 0.0001
penalty: 0.0001
validation_steps: 5
early_stop:
  patience: 5
  monitor: val_loss
loss: categorical_crossentropy
metrics:
  - categorical_accuracy
